"""init

Revision ID: c7f802a87863
Revises: 
Create Date: 2026-01-06 13:17:59.365966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7f802a87863'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('niveau_etudes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sexes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('situations_familiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('taille', sa.Float(), nullable=True),
    sa.Column('poids', sa.Float(), nullable=True),
    sa.Column('sexe_id', sa.Integer(), nullable=True),
    sa.Column('sport_licence', sa.Boolean(), nullable=True),
    sa.Column('niveau_etude_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('fumeur', sa.Boolean(), nullable=True),
    sa.Column('nationalite_francaise', sa.Boolean(), nullable=True),
    sa.Column('revenu_estime_mois', sa.Integer(), nullable=True),
    sa.Column('situation_familiale_id', sa.Integer(), nullable=True),
    sa.Column('historique_credits', sa.Float(), nullable=True),
    sa.Column('risque_personnel', sa.Float(), nullable=True),
    sa.Column('date_creation_compte', sa.Date(), nullable=True),
    sa.Column('score_credit', sa.Float(), nullable=True),
    sa.Column('loyer_mensuel', sa.Float(), nullable=True),
    sa.Column('montant_pret', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['niveau_etude_id'], ['niveau_etudes.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['sexe_id'], ['sexes.id'], ),
    sa.ForeignKeyConstraint(['situation_familiale_id'], ['situations_familiales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    op.drop_table('situations_familiales')
    op.drop_table('sexes')
    op.drop_table('regions')
    op.drop_table('niveau_etudes')
    # ### end Alembic commands ###
